### ISSUE TITLE
feat: Mistral AI support (user-provided API key)

### ISSUE THREAD

**Issue by jakobgraetz** [johannesschiessl/AI-CLI-Tool#4]
![image](https://github.com/johannesschiessl/AI-Assistant/assets/96118933/c04ad75f-ff13-4183-9939-6830a8461b08)

[Mistral AI](https://mistral.ai/product/)

Mistral's API integrates fully into OpenAI API compatible code.

### Benefits
- easy to integrate
- powerful models
- user-friendly
- developer-friendly

**Comment by johannesschiessl** [comment]
Great idea, I will definitely add that to the roadmap.
